include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
errors:
  invalid_annotation_target: ignore
  missing_required_param: warning
  missing_return: warning
  